# Generated by Django 5.1.7 on 2025-04-07 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shopID', models.CharField(editable=False, max_length=6, primary_key=True, serialize=False)),
                ('shopName', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('industry', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.CharField(editable=False, max_length=7, primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=20)),
                ('Lname', models.CharField(max_length=20)),
                ('nationalID', models.CharField(max_length=20, unique=True)),
                ('DoB', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phoneNo', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeID', models.CharField(editable=False, max_length=6, primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=20)),
                ('Lname', models.CharField(max_length=20)),
                ('nationalID', models.CharField(max_length=20, unique=True)),
                ('DoB', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('shopID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invex.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('productID', models.CharField(editable=False, max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default='NULL')),
                ('manufacturer', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('shopID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invex.shop')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invex.user'),
        ),
    ]
