# Generated by Django 5.1.7 on 2025-04-19 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invex', '0004_alter_user_is_active_emailveridicationtoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailVeridicationToken',
            new_name='EmailVerificationToken',
        ),
    ]
