# Generated by Django 5.1.7 on 2025-04-20 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invex', '0005_rename_emailveridicationtoken_emailverificationtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
